---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret_kustomization.yaml
  - ingress_kustomization.yaml
  - network_policy.yaml
  - frontend/deployment.yaml
  - frontend/hpa.yaml
  - frontend/pdb.yaml
  - frontend/service.yaml
  - frontend/ingress.yaml
