---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beeswarm-api
  namespace: beeswarm
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
        - api.ai.login.no
  rules:
    - host: api.ai.login.no
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: beeswarm-api
                port:
                  number: 8080
