---
apiVersion: v1
kind: Service
metadata:
  name: beeswarm-frontend
  namespace: beeswarm
  labels:
    app: beeswarm-frontend
spec:
  type: ClusterIP
  selector:
    app: beeswarm-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
