---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://github.com/orgs/Login-Linjeforening-for-IT/
  name: github-redirect-ingress
  namespace: redirect-namespace
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
      - github.login.no
  rules:
    - host: github.login.no
