---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($remote_addr !~ "^129\.241\.") {
        return 301 https://login.no$request_uri;
      }
  name: queenbee-external-redirect
  namespace: queenbee
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
        - queenbee.login.no
  rules:
    - host: queenbee.login.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: queenbee-frontend
                port:
                  number: 3000