---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://login.no/vpn
  name: vpn-redirect-ingress
  namespace: redirect-namespace
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
      - queenbee.login.no
  rules:
    - host: queenbee.login.no
