---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://login.no/vpn
    external-dns.alpha.kubernetes.io/hostname: dev.queenbee.login.no
  name: vpn-redirect-ingress
  namespace: redirect-namespace
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
      - dev.queenbee.login.no
  rules:
    - host: dev.queenbee.login.no
