---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workerbee
  namespace: workerbee
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
        - workerbee.login.no
  rules:
    - host: workerbee.login.no
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: workerbee
                port:
                  number: 8080
